### PR TITLE
Romanian translation available

### PR DESCRIPTION
**Pull request by vlad-ghita**
Hi.

I added romanian translation to your extension and the translation function to the navigation item. Could you please integrate them?

Thank you.

### CODE REVIEW

**Comment by bauhouse** [comment]
Thanks for the pull request. But, it appears that [the convention](http://symphony-cms.com/discuss/thread/61413/) is to NOT translate extension names.

**Comment by bauhouse** [comment]
[Nick set me straight](http://symphony-cms.com/discuss/thread/61413/1/#position-10). I had to learn a little about how to set up the extension for localization. I've pulled in the changes you requested. But I've also added the ability to translate the "Save Settings" button. I've already updated to [version 1.3.3](http://symphony-cms.com/download/extensions/view/26792/). But, if you want to add the translation for the button, the success alert and the error alert, feel free to send me another pull request.

**Comment by vlad-ghita** [comment]
Thanks for integrating. I'll send a pull request asap.

**Comment by bauhouse** [comment]
I've integrated your changes into version 1.3.4. Thanks! (And sorry it took so long to integrate.)

**Comment by vlad-ghita** [comment]
>  And sorry it took so long to integrate

No prob.

**Pull request closed without merging**
